version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
      # copy the sql script to write the data
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: ["postgres", "-c", "log_statement=all"]
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: "dracula"
    ports:
      - 8090:8080
